# Generated by Django 4.2.16 on 2024-11-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='title',
        ),
    ]
